export const demos = [
  {
    id: "subtext-chat",
    titleKey: "demo9" as const,
    path: "/demos/subtext-chat",
    icon: "🎯",
    descriptionEn: "Live subtext radar with chat + conditions engine",
    descriptionHe: "רדאר סאבטקסט חי עם צ׳אט ומנוע תנאים",
    featured: true,
  },
  {
    id: "inbox-triage",
    titleKey: "demo1" as const,
    path: "/demos/inbox-triage",
    icon: "📡",
    descriptionEn: "Multi-axis parallel triage with confidence-gated routing",
    descriptionHe: "טריאז׳ רב-ציר מקבילי עם ניתוב מבוסס ביטחון",
  },
  {
    id: "prompt-injection",
    titleKey: "demo2" as const,
    path: "/demos/prompt-injection",
    icon: "🛡️",
    descriptionEn: "Semantic firewall for RAG pipelines",
    descriptionHe: "חומת אש סמנטית לצינורות RAG",
  },
  {
    id: "citation-check",
    titleKey: "demo3" as const,
    path: "/demos/citation-check",
    icon: "✓",
    descriptionEn: "Verify claims against evidence with confidence thresholds",
    descriptionHe: "אימות טענות מול ראיות עם סף ביטחון",
  },
  {
    id: "model-router",
    titleKey: "demo4" as const,
    path: "/demos/model-router",
    icon: "💰",
    descriptionEn: "Route to the right model tier based on task properties",
    descriptionHe: "ניתוב לרמת המודל הנכונה לפי מאפייני המשימה",
  },
  {
    id: "marketplace-cop",
    titleKey: "demo5" as const,
    path: "/demos/marketplace-cop",
    icon: "🚨",
    descriptionEn: "Automated content policy enforcement",
    descriptionHe: "אכיפת מדיניות תוכן אוטומטית",
  },
  {
    id: "tos-finder",
    titleKey: "demo6" as const,
    path: "/demos/tos-finder",
    icon: "🔍",
    descriptionEn: "Semantic search across document lines",
    descriptionHe: "חיפוש סמנטי על פני שורות מסמך",
  },
  {
    id: "moderation",
    titleKey: "demo7" as const,
    path: "/demos/moderation",
    icon: "⚡",
    descriptionEn: "Real-time content moderation matrix",
    descriptionHe: "מטריצת מודרציה בזמן אמת",
  },
  {
    id: "icp-scorer",
    titleKey: "demo8" as const,
    path: "/demos/icp-scorer",
    icon: "🎯",
    descriptionEn: "Composite scoring with adjustable weights",
    descriptionHe: "ניקוד מורכב עם משקלים ניתנים לכוונון",
  },
  {
    id: "money-hack-finder",
    titleKey: "demo17" as const,
    path: "/demos/money-hack-finder",
    icon: "💰",
    descriptionEn: "AI-powered idea evolution loop with atomic scoring",
    descriptionHe: "לולאת אבולוציה לרעיונות עם ניקוד אטומי מופעל ע״י AI",
    featured: true,
  },
];